### ISSUE TITLE
Please add requirements.txt file  

### ISSUE THREAD

**Issue by manishbajjuri** [nitesh31mishra/Face-Recognition-system#1]
** Please add IDE which you have used for developed along with there versions**

**Comment by nitesh31mishra** [comment]
Actually here I haven't created any virtual environment for my project I
have just used the (base) environment in anaconda so the requirement.txt
file contains all the libraries which won't help you.Specifically I have
used
opencv-contrib-python ==4.4.0.42
opencv-python ==4.2.0.34

Rest all are just basic libraries
If you want I can share you the requirement file but it consists of all
libraries

**Comment by nitesh31mishra** [comment]
I have added reuirements file.

**Comment by manishbajjuri** [comment]
okay thank you
